version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: pure
      POSTGRES_DB: pure
      POSTGRES_PASSWORD: pure1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u pure"]
      interval: 6s
      timeout: 6s
      retries: 10
  pure:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: